### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by NelminDev** [inef1337/based#3]
Hey!
I get [multiple errors](https://www.toptal.com/developers/hastebin) while in the build process.

I use Visual Studio 2022, Newest Version

**Comment by inef1337** [comment]
Hi Nelmin,

I tried accessing the hastebin you provided, but unfortunately, it appears to be empty. As a result, I am not sure about the exact errors you're facing. However, based on the information you provided, the problem could be caused by a couple of things.

Firstly, it's possible that you're compiling in x86 mode, which may not have been properly set up as the application is designed for x64 bit architecture. Moreover, the x64 mode may have only been configured for the release mode. Alternatively, the issue could be related to a missing dependency required to build the project. You can find the dependency link in the project description under the 'dependencies' section. Once you have installed the dependency, you need to link it to the project by configuring the VC++ Directories section in the project properties.

In hopes of helping you further, I have included a couple of pictures that display what the property settings should look like.

![img2](https://user-images.githubusercontent.com/130789342/233066623-4c9cbd87-2a18-44da-84bb-57d401abf379.PNG)
![img1](https://user-images.githubusercontent.com/130789342/233066662-eff89383-2056-4907-95b6-41961d2733a8.PNG)

I hope this helps. Please let me know if you have any other questions.

**Comment by NelminDev** [comment]
It's working now, but I have a other quick question: How can I change the open hotkey?

**Comment by inef1337** [comment]
![bruh](https://user-images.githubusercontent.com/130789342/233838575-46973c53-14f1-4869-a472-b7d2674ee463.PNG)
